ALTER TABLE checkout_sessions ADD COLUMN discounts TEXT NOT NULL DEFAULT '[]';
ALTER TABLE invoices ADD COLUMN discount_amount INTEGER NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN discounts TEXT NOT NULL DEFAULT '[]';
