ALTER TABLE checkout_sessions ADD COLUMN automatic_tax INTEGER NOT NULL DEFAULT 0;
ALTER TABLE checkout_sessions ADD COLUMN tax_id_collection INTEGER NOT NULL DEFAULT 0;
ALTER TABLE checkout_sessions ADD COLUMN tax_percent REAL NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN automatic_tax INTEGER NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN tax INTEGER NOT NULL DEFAULT 0;
